export const projects = [
  {
    id: "11",
    year: "2026",
    title: "MiniGPT-Shakespeare: Trained GPT Model for Text Generation",
    link: "https://huggingface.co/spaces/m-lagnajit/minigpt-shakespeare",
    github:
      "https://github.com/Lagnajit09/100x_AI_ML/tree/main/minigpt-model-hf",
    tech: ["PyTorch", "Gradio", "HuggingFace", "Transformers & Attention"],
  },
  {
    id: "10",
    year: "2025 - 2026",
    title: "AutoSage Docs",
    link: "https://autosagexdocs.web.app/",
    github: "https://github.com/Lagnajit09/autosage-docs",
    tech: ["Docusaurus", "Django", "RAG", "Supabase - VectorDB"],
  },
  {
    id: "9",
    year: "2025 - 2026",
    title: "AutoSage: Infrastructure Automation Platform",
    link: "https://autosagex.web.app/",
    github: "https://github.com/Lagnajit09/autosage",
    tech: [
      "ReactJS",
      "Django",
      "Redis",
      "Celery",
      "GCP",
      "Tailwind CSS",
      "RAG",
      "Agentic AI",
      "Supabase",
      "Docker",
    ],
  },
  {
    id: "8",
    year: "2025",
    title: "SwiftPay - InfraOps",
    link: "",
    github: "https://github.com/Lagnajit09/swiftpay-infraops",
    tech: [
      "NextJS",
      "ExpressJS",
      "PostgreSQL",
      "Tailwind CSS",
      "Prisma",
      "Microservices",
      "Docker",
    ],
  },
  {
    id: "7",
    year: "2024 - 2025",
    title: "SwiftPay",
    link: "https://swiftpaylm.vercel.app/",
    github: "https://github.com/Lagnajit09/walletX",
    tech: ["NextJS", "ExpressJS", "PostgreSQL", "Tailwind CSS", "Prisma"],
  },
  {
    id: "2",
    year: "2024",
    title: "Medium: Blogging website",
    link: "https://medium-pro.web.app/",
    github: "https://github.com/Lagnajit09/Medium",
    tech: ["ReactJS", "postgreSQL", "CloudFlare", "Prisma ORM", "Tailwind CSS"],
  },
  {
    id: "3",
    year: "2024",
    title: "Aora: Android application",
    link: "",
    github: "https://github.com/Lagnajit09/Aora-ReactNative",
    tech: ["ReactNative", "appwrite", "Tailwind CSS"],
  },
  {
    id: "4",
    year: "2024",
    title: "Figma: Desiging platform",
    link: "https://pro-figma.vercel.app/",
    github: "https://github.com/Lagnajit09/Figma",
    tech: ["NextJS", "Liveblocks", "Tailwind CSS", "Typescript"],
  },
  {
    id: "5",
    year: "2024",
    title: "Resume Portfolio",
    link: "https://lagnajitmoharana08.web.app/",
    github: "https://github.com/Lagnajit09/lagnajitmoharana.com",
    tech: ["ReactJS", "Tailwind CSS"],
  },
];

export const topProjects = [
  {
    title: "AutoSage: Infrastructure Automation Platform",
    link: "https://autosagex.web.app/",
    tech: [
      "ReactJS",
      "Django",
      "Redis",
      "Celery",
      "GCP",
      "Tailwind CSS",
      "RAG",
      "Agentic AI",
      "Supabase",
      "Docker",
    ],
    description:
      "AutoSage is an AI-driven infrastructure automation platform that streamlines and optimizes cloud operations through workflows, RAG and agentic AI, enabling users to manage and scale their infrastructure efficiently.",
  },
  {
    title: "MiniGPT-Shakespeare: Trained GPT Model for Text Generation",
    link: "https://huggingface.co/spaces/m-lagnajit/minigpt-shakespeare",
    tech: ["PyTorch", "Gradio", "HuggingFace", "Transformers & Attention"],
    description:
      "MiniGPT-Shakespeare is a specialized GPT model trained to generate text in the style of William Shakespeare. Built a transformer-based architecture using PyTorch and fine-tuned it on a curated dataset of Shakespearean works, enabling it to produce authentic and stylistically accurate text.",
  },
  {
    title: "Swiftpay: Payment Application",
    link: "https://swiftpaylm.vercel.app/",
    tech: ["NextJS", "ExpressJS", "PostgreSQL", "Tailwind CSS", "Prisma"],
    description:
      "SwiftPay is a demo payment application that allows users to send and receive money instantly, connect with friends, and manage their finances with ease. It is built with a modern tech stack and offers a seamless user experience.",
  },
];
