export const projects = [
  {
    id: "1",
    year: "2024",
    title: "StudyBuddy: Virtual study platform",
    link: "https://studybuddy-52816.web.app/",
    github: "https://github.com/Lagnajit09/StudyBuddy",
    tech: ["ReactJS", "ExpressJS", "MongoDB", "Firebase", "Socket.io"],
  },
  {
    id: "2",
    year: "2024",
    title: "Medium: Blogging website",
    link: "https://medium-pro.web.app/",
    github: "https://github.com/Lagnajit09/Medium",
    tech: ["ReactJS", "postgreSQL", "CloudFlare", "Prisma ORM", "Tailwind CSS"],
  },
  {
    id: "3",
    year: "2024",
    title: "Aora: Android application",
    link: "",
    github: "https://github.com/Lagnajit09/Aora-ReactNative",
    tech: ["ReactNative", "appwrite", "Tailwind CSS"],
  },
  {
    id: "4",
    year: "2024",
    title: "Figma: Desiging platform",
    link: "https://pro-figma.vercel.app/",
    github: "https://github.com/Lagnajit09/Figma",
    tech: ["NextJS", "Liveblocks", "Tailwind CSS", "Typescript"],
  },
  {
    id: "5",
    year: "2024",
    title: "Resume Portfolio",
    link: "https://pro-figma.vercel.app/",
    github: "https://github.com/Lagnajit09/lagnajitmoharana.com",
    tech: ["ReactJS", "Tailwind CSS"],
  },
  {
    id: "6",
    year: "2023",
    title: "Social Media Template",
    link: "https://ls-book.web.app/",
    github: "https://github.com/Lagnajit09/social-media",
    tech: ["ReactJS", "Firebase"],
  },
];
